"""Task materials: reference documents (input) and deliverables (output) attached to an owned Task.

Bytes are stored behind the MaterialStorage port; the Work ledger keeps identity, kind, and provenance.
The local-directory adapter is the first implementation and an Azure Blob container adapter will
implement the same port without touching this module.
"""
from __future__ import annotations

from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import UUID, uuid4

from ax_workspace.modules.organization_access.domain import Principal, TASK_READ, TASK_SELF_MANAGE
from ax_workspace.modules.work.application import TaskAccessDenied, TaskError, TaskRepository

MATERIAL_KINDS = frozenset({"input", "output"})
MAX_MATERIAL_BYTES = 25 * 1024 * 1024


class MaterialError(TaskError):
    pass


class MaterialNotFound(MaterialError):
    pass


class MaterialStorage(Protocol):
    """Content-addressed blob store; keys are generated by the application, never by callers."""

    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...


class TaskMaterialRepository(Protocol):
    def add(
        self,
        *,
        task_id: UUID,
        kind: str,
        name: str,
        content_type: str,
        size_bytes: int,
        storage_key: str,
        uploaded_by: str,
    ) -> Any: ...
    def list_for(self, task_id: UUID) -> list[Any]: ...
    def get(self, task_id: UUID, material_id: UUID) -> Any | None: ...


class TaskMaterialApplication:
    def __init__(self, tasks: TaskRepository, materials: TaskMaterialRepository, storage: MaterialStorage) -> None:
        self._tasks = tasks
        self._materials = materials
        self._storage = storage

    def list(self, principal: Principal, task_id: UUID) -> list[dict[str, Any]]:
        self._require(principal, TASK_READ)
        self._tasks.task(task_id, str(principal.id))
        return [self._view(item) for item in self._materials.list_for(task_id) if item.removed_at is None]

    def attach(
        self,
        principal: Principal,
        task_id: UUID,
        *,
        kind: str,
        name: str,
        content_type: str,
        data: bytes,
    ) -> dict[str, Any]:
        self._require(principal, TASK_SELF_MANAGE)
        task = self._tasks.task(task_id, str(principal.id), lock=True)
        if kind not in MATERIAL_KINDS:
            raise MaterialError("material kind must be input or output")
        clean_name = name.strip().replace("/", "_").replace("\\", "_")[:300]
        if not clean_name:
            raise MaterialError("material name is required")
        if not data:
            raise MaterialError("material content is empty")
        if len(data) > MAX_MATERIAL_BYTES:
            raise MaterialError("material exceeds the 25MB limit")
        storage_key = f"tasks/{task.id}/{uuid4()}"
        self._storage.put(storage_key, data, content_type or "application/octet-stream")
        record = self._materials.add(
            task_id=task.id,
            kind=kind,
            name=clean_name,
            content_type=content_type or "application/octet-stream",
            size_bytes=len(data),
            storage_key=storage_key,
            uploaded_by=str(principal.id),
        )
        return self._view(record)

    def open(self, principal: Principal, task_id: UUID, material_id: UUID) -> tuple[dict[str, Any], bytes]:
        self._require(principal, TASK_READ)
        self._tasks.task(task_id, str(principal.id))
        record = self._materials.get(task_id, material_id)
        if record is None or record.removed_at is not None:
            raise MaterialNotFound("material was not found")
        return self._view(record), self._storage.get(record.storage_key)

    def detach(self, principal: Principal, task_id: UUID, material_id: UUID) -> dict[str, Any]:
        """Materials are never edited in place: detach keeps the record and bytes for lineage."""
        self._require(principal, TASK_SELF_MANAGE)
        self._tasks.task(task_id, str(principal.id), lock=True)
        record = self._materials.get(task_id, material_id)
        if record is None or record.removed_at is not None:
            raise MaterialNotFound("material was not found")
        record.removed_at = datetime.now(UTC)
        return self._view(record)

    @staticmethod
    def _require(principal: Principal, capability: str) -> None:
        if capability not in principal.capabilities:
            raise TaskAccessDenied(f"{capability} capability is required")

    @staticmethod
    def _view(record: Any) -> dict[str, Any]:
        return {
            "material_id": str(record.id),
            "task_id": str(record.task_id),
            "kind": record.kind,
            "name": record.name,
            "content_type": record.content_type,
            "size_bytes": int(record.size_bytes),
            "uploaded_by": record.uploaded_by,
            "created_at": record.created_at.isoformat(),
            "removed_at": record.removed_at.isoformat() if record.removed_at else None,
        }
